import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT_PATH = process.cwd();
const TOKENS_PATH = path.resolve(ROOT_PATH, 'src/app/styles/tokens');
const CONTRACTS_PATH = path.resolve(ROOT_PATH, 'src/app/styles/contracts');

const FILE_HEADER = (sourceFile) => [
  '// This file is auto-generated by scripts/generators/generateStyleContracts.js.',
  `// Do not edit it manually. Update ${sourceFile} and regenerate instead.`,
  '',
].join('\n');

const COLOR_GROUP_NAMES = [
  'PALETTE_COLOR_TOKENS',
  'BRAND_COLOR_TOKENS',
  'SURFACE_COLOR_TOKENS',
  'BORDER_COLOR_TOKENS',
  'TEXT_COLOR_TOKENS',
  'ICON_COLOR_TOKENS',
  'STATUS_COLOR_TOKENS',
];

async function readTokenFile(fileName) {
  return readFile(path.resolve(TOKENS_PATH, fileName), 'utf8');
}

function extractStringTokens(source, prefix) {
  return [...source.matchAll(new RegExp(`--${prefix}([a-z0-9-]+)\\s*:`, 'g'))]
    .map((match) => match[1]);
}

function extractNumberTokens(source, prefix) {
  return [...source.matchAll(new RegExp(`--${prefix}(\\d+)\\s*:`, 'g'))]
    .map((match) => Number(match[1]));
}

function toTypeName(name) {
  return name
    .toLowerCase()
    .split(/[^a-z0-9]+/g)
    .filter(Boolean)
    .map((chunk) => chunk[0].toUpperCase() + chunk.slice(1))
    .join('');
}

function renderConstArray(name, values) {
  if (values.length === 0) {
    return `export const ${name} = [] as const;\n`;
  }

  const renderedValues = values
    .map((value) => (typeof value === 'number' ? `  ${value},` : `  '${value}',`))
    .join('\n');

  return `export const ${name} = [\n${renderedValues}\n] as const;\n`;
}

function renderStringTokenSet(constName) {
  return `const ${constName}_SET = new Set<string>(${constName});\n`;
}

function renderNumberTokenSet(constName) {
  return `const ${constName}_SET = new Set<number>(${constName});\n`;
}

function renderTypeAlias(name, constName) {
  return `export type ${name} = (typeof ${constName})[number];\n`;
}

function renderUnionType(name, values) {
  return `export type ${name} =\n${values.map((value) => `  | ${value}`).join('\n')};\n`;
}

function renderColorContract(colorTokens) {
  const groups = {
    PALETTE_COLOR_TOKENS: colorTokens.filter((token) => token.startsWith('blind-')),
    BRAND_COLOR_TOKENS: colorTokens.filter((token) => (
      ['primary', 'primary-hover', 'primary-pressed', 'on-primary', 'success', 'warning', 'error', 'info'].includes(token)
    )),
    SURFACE_COLOR_TOKENS: colorTokens.filter((token) => token === 'background' || token.startsWith('surface-')),
    BORDER_COLOR_TOKENS: colorTokens.filter((token) => token.startsWith('border-')),
    TEXT_COLOR_TOKENS: colorTokens.filter((token) => token.startsWith('text-')),
    ICON_COLOR_TOKENS: colorTokens.filter((token) => token.startsWith('icon-')),
    STATUS_COLOR_TOKENS: colorTokens.filter((token) => (
      token.endsWith('-text') || token.endsWith('-background')
    )),
  };

  const content = [
    FILE_HEADER('src/app/styles/tokens/colors.css'),
    ...COLOR_GROUP_NAMES.map((name) => renderConstArray(name, groups[name])),
    renderConstArray(
      'COLOR_TOKENS',
      COLOR_GROUP_NAMES.map((name) => `...${name}`),
    ).replace(/'(\.\.\.[A-Z_]+)'/g, '$1'),
    ...COLOR_GROUP_NAMES.map((name) => renderTypeAlias(`t${toTypeName(name.replace(/_TOKENS$/, '').toLowerCase())}Token`, name)),
    renderUnionType('tColorToken', COLOR_GROUP_NAMES.map((name) => `t${toTypeName(name.replace(/_TOKENS$/, '').toLowerCase())}Token`)),
    renderUnionType('tColorValue', [
      'tColorToken',
      '`var(--${string})`',
      '`#${string}`',
      '`rgb(${string})`',
      '`rgba(${string})`',
      '`hsl(${string})`',
      '`hsla(${string})`',
      '`color-mix(${string})`',
      "'currentColor'",
      "'transparent'",
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ]),
    renderStringTokenSet('COLOR_TOKENS'),
    [
      'export function isColorToken(value: string): value is tColorToken {',
      '  return COLOR_TOKENS_SET.has(value);',
      '}',
      '',
      'export function colorTokenVar(token: tColorToken): `var(--app-color-${tColorToken})` {',
      '  return `var(--app-color-${token})`;',
      '}',
      '',
      'export function resolveColorValue(color?: tColorValue) {',
      '  if (!color) {',
      '    return undefined;',
      '  }',
      '',
      '  return isColorToken(color) ? colorTokenVar(color) : color;',
      '}',
      '',
    ].join('\n'),
  ].join('\n');

  return content;
}

function renderSimpleStringContract({
  sourceFile,
  constName,
  typeName,
  valueTypeName,
  tokens,
  varPrefix,
  extras,
  resolverName,
  tokenVarName,
  checkerName,
}) {
  return [
    FILE_HEADER(sourceFile),
    renderConstArray(constName, tokens),
    renderTypeAlias(typeName, constName),
    renderUnionType(valueTypeName, [typeName, ...extras]),
    renderStringTokenSet(constName),
    [
      `export function ${checkerName}(value: string): value is ${typeName} {`,
      `  return ${constName}_SET.has(value);`,
      '}',
      '',
      `export function ${tokenVarName}(token: ${typeName}): \`var(--${varPrefix}-\${${typeName}})\` {`,
      `  return \`var(--${varPrefix}-\${token})\`;`,
      '}',
      '',
      `export function ${resolverName}(value?: ${valueTypeName}) {`,
      '  if (!value) {',
      '    return undefined;',
      '  }',
      '',
      `  return ${checkerName}(value) ? ${tokenVarName}(value) : value;`,
      '}',
      '',
    ].join('\n'),
  ].join('\n');
}

function renderSimpleNumberContract({
  sourceFile,
  constName,
  typeName,
  valueTypeName,
  tokens,
  varPrefix,
  extras,
  resolverName,
  tokenVarName,
  checkerName,
}) {
  return [
    FILE_HEADER(sourceFile),
    renderConstArray(constName, tokens),
    renderTypeAlias(typeName, constName),
    renderUnionType(valueTypeName, [typeName, ...extras]),
    renderNumberTokenSet(constName),
    [
      `export function ${checkerName}(value: number): value is ${typeName} {`,
      `  return ${constName}_SET.has(value);`,
      '}',
      '',
      `export function ${tokenVarName}(token: ${typeName}): \`var(--${varPrefix}-\${${typeName}})\` {`,
      `  return \`var(--${varPrefix}-\${token})\`;`,
      '}',
      '',
      `export function ${resolverName}(value?: ${valueTypeName}) {`,
      '  if (value === undefined || value === null) {',
      '    return undefined;',
      '  }',
      '',
      `  return typeof value === 'number' && ${checkerName}(value) ? ${tokenVarName}(value) : value;`,
      '}',
      '',
    ].join('\n'),
  ].join('\n');
}

function renderBorderContract(borderWidthTokens, borderStyleTokens) {
  return [
    FILE_HEADER('src/app/styles/tokens/borders.css'),
    renderConstArray('BORDER_WIDTH_TOKENS', borderWidthTokens),
    renderConstArray('BORDER_STYLE_TOKENS', borderStyleTokens),
    renderTypeAlias('tBorderWidthToken', 'BORDER_WIDTH_TOKENS'),
    renderTypeAlias('tBorderStyleToken', 'BORDER_STYLE_TOKENS'),
    renderUnionType('tBorderWidthValue', [
      'tBorderWidthToken',
      '`var(--${string})`',
      '`${number}px`',
      '`${number}rem`',
      '`calc(${string})`',
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ]),
    renderUnionType('tBorderStyleValue', [
      'tBorderStyleToken',
      "'dotted'",
      "'double'",
      "'none'",
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ]),
    renderStringTokenSet('BORDER_WIDTH_TOKENS'),
    renderStringTokenSet('BORDER_STYLE_TOKENS'),
    [
      'export function isBorderWidthToken(value: string): value is tBorderWidthToken {',
      '  return BORDER_WIDTH_TOKENS_SET.has(value);',
      '}',
      '',
      'export function isBorderStyleToken(value: string): value is tBorderStyleToken {',
      '  return BORDER_STYLE_TOKENS_SET.has(value);',
      '}',
      '',
      'export function borderWidthTokenVar(token: tBorderWidthToken): `var(--app-border-width-${tBorderWidthToken})` {',
      '  return `var(--app-border-width-${token})`;',
      '}',
      '',
      'export function borderStyleTokenVar(token: tBorderStyleToken): `var(--app-border-style-${tBorderStyleToken})` {',
      '  return `var(--app-border-style-${token})`;',
      '}',
      '',
      'export function resolveBorderWidthValue(borderWidth?: tBorderWidthValue) {',
      '  if (!borderWidth) {',
      '    return undefined;',
      '  }',
      '',
      '  return isBorderWidthToken(borderWidth) ? borderWidthTokenVar(borderWidth) : borderWidth;',
      '}',
      '',
      'export function resolveBorderStyleValue(borderStyle?: tBorderStyleValue) {',
      '  if (!borderStyle) {',
      '    return undefined;',
      '  }',
      '',
      '  return isBorderStyleToken(borderStyle) ? borderStyleTokenVar(borderStyle) : borderStyle;',
      '}',
      '',
    ].join('\n'),
  ].join('\n');
}

async function writeContract(fileName, content) {
  const filePath = path.resolve(CONTRACTS_PATH, fileName);
  await writeFile(filePath, content, 'utf8');
  console.log(`Updated ${path.relative(ROOT_PATH, filePath)}`);
}

async function generateStyleContracts() {
  const colorsSource = await readTokenFile('colors.css');
  const typographySource = await readTokenFile('typography.css');
  const radiusSource = await readTokenFile('radius.css');
  const spacingSource = await readTokenFile('spacing.css');
  const paddingSource = await readTokenFile('padding.css');
  const bordersSource = await readTokenFile('borders.css');

  await writeContract('color.contract.ts', renderColorContract(extractStringTokens(colorsSource, 'app-color-')));
  await writeContract('fontSize.contract.ts', renderSimpleStringContract({
    sourceFile: 'src/app/styles/tokens/typography.css',
    constName: 'FONT_SIZE_TOKENS',
    typeName: 'tFontSizeToken',
    valueTypeName: 'tFontSizeValue',
    tokens: extractStringTokens(typographySource, 'app-font-size-'),
    varPrefix: 'app-font-size',
    extras: [
      '`var(--${string})`',
      '`${number}px`',
      '`${number}rem`',
      '`${number}em`',
      '`${number}%`',
      '`calc(${string})`',
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ],
    resolverName: 'resolveFontSizeValue',
    tokenVarName: 'fontSizeTokenVar',
    checkerName: 'isFontSizeToken',
  }));
  await writeContract('fontWeight.contract.ts', renderSimpleStringContract({
    sourceFile: 'src/app/styles/tokens/typography.css',
    constName: 'FONT_WEIGHT_TOKENS',
    typeName: 'tFontWeightToken',
    valueTypeName: 'tFontWeightValue',
    tokens: extractStringTokens(typographySource, 'app-font-weight-'),
    varPrefix: 'app-font-weight',
    extras: [
      '100',
      '200',
      '300',
      '400',
      '500',
      '600',
      '700',
      '800',
      '900',
      "'normal'",
      "'bold'",
      "'bolder'",
      "'lighter'",
      "'inherit'",
      "'initial'",
      "'unset'",
    ],
    resolverName: 'resolveFontWeightValue',
    tokenVarName: 'fontWeightTokenVar',
    checkerName: 'isFontWeightToken',
  }).replace(
    '  return isFontWeightToken(value) ? fontWeightTokenVar(value) : value;',
    "  return typeof value === 'string' && isFontWeightToken(value)\n    ? fontWeightTokenVar(value)\n    : value;",
  ));
  await writeContract('radius.contract.ts', renderSimpleStringContract({
    sourceFile: 'src/app/styles/tokens/radius.css',
    constName: 'RADIUS_TOKENS',
    typeName: 'tRadiusToken',
    valueTypeName: 'tRadiusValue',
    tokens: extractStringTokens(radiusSource, 'app-radius-'),
    varPrefix: 'app-radius',
    extras: [
      '`var(--${string})`',
      '`${number}px`',
      '`${number}rem`',
      '`${number}%`',
      '`calc(${string})`',
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ],
    resolverName: 'resolveRadiusValue',
    tokenVarName: 'radiusTokenVar',
    checkerName: 'isRadiusToken',
  }));
  await writeContract('space.contract.ts', renderSimpleNumberContract({
    sourceFile: 'src/app/styles/tokens/spacing.css',
    constName: 'SPACE_TOKENS',
    typeName: 'tSpaceToken',
    valueTypeName: 'tSpaceValue',
    tokens: extractNumberTokens(spacingSource, 'app-space-'),
    varPrefix: 'app-space',
    extras: [
      '`var(--${string})`',
      '`${number}px`',
      '`${number}rem`',
      '`${number}%`',
      '`calc(${string})`',
      "'auto'",
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ],
    resolverName: 'resolveSpaceValue',
    tokenVarName: 'spaceTokenVar',
    checkerName: 'isSpaceToken',
  }));
  await writeContract('padding.contract.ts', renderSimpleNumberContract({
    sourceFile: 'src/app/styles/tokens/padding.css',
    constName: 'PADDING_TOKENS',
    typeName: 'tPaddingToken',
    valueTypeName: 'tPaddingValue',
    tokens: extractNumberTokens(paddingSource, 'app-padding-'),
    varPrefix: 'app-padding',
    extras: [
      '`var(--${string})`',
      '`${number}px`',
      '`${number}rem`',
      '`${number}%`',
      '`calc(${string})`',
      "'inherit'",
      "'initial'",
      "'unset'",
      '(string & {})',
    ],
    resolverName: 'resolvePaddingValue',
    tokenVarName: 'paddingTokenVar',
    checkerName: 'isPaddingToken',
  }));
  await writeContract('border.contract.ts', renderBorderContract(
    extractStringTokens(bordersSource, 'app-border-width-'),
    extractStringTokens(bordersSource, 'app-border-style-'),
  ));

  console.log('Style contracts generated successfully');
}

generateStyleContracts().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
