// This file is auto-generated by scripts/generators/generateStyleContracts.js.
// Do not edit it manually. Update src/app/styles/tokens/typography.css and regenerate instead.

export const FONT_WEIGHT_TOKENS = [
  'regular',
  'medium',
  'semibold',
  'bold',
] as const;

export type tFontWeightToken = (typeof FONT_WEIGHT_TOKENS)[number];

export type tFontWeightValue =
  | tFontWeightToken
  | 100
  | 200
  | 300
  | 400
  | 500
  | 600
  | 700
  | 800
  | 900
  | 'normal'
  | 'bold'
  | 'bolder'
  | 'lighter'
  | 'inherit'
  | 'initial'
  | 'unset';

const FONT_WEIGHT_TOKENS_SET = new Set<string>(FONT_WEIGHT_TOKENS);

export function isFontWeightToken(value: string): value is tFontWeightToken {
  return FONT_WEIGHT_TOKENS_SET.has(value);
}

export function fontWeightTokenVar(token: tFontWeightToken): `var(--app-font-weight-${tFontWeightToken})` {
  return `var(--app-font-weight-${token})`;
}

export function resolveFontWeightValue(value?: tFontWeightValue) {
  if (!value) {
    return undefined;
  }

  return typeof value === 'string' && isFontWeightToken(value)
    ? fontWeightTokenVar(value)
    : value;
}
