// This file is auto-generated by scripts/generators/generateStyleContracts.js.
// Do not edit it manually. Update src/app/styles/tokens/padding.css and regenerate instead.

export const PADDING_TOKENS = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
] as const;

export type tPaddingToken = (typeof PADDING_TOKENS)[number];

export type tPaddingValue =
  | tPaddingToken
  | `var(--${string})`
  | `${number}px`
  | `${number}rem`
  | `${number}%`
  | `calc(${string})`
  | 'inherit'
  | 'initial'
  | 'unset'
  | (string & {});

const PADDING_TOKENS_SET = new Set<number>(PADDING_TOKENS);

export function isPaddingToken(value: number): value is tPaddingToken {
  return PADDING_TOKENS_SET.has(value);
}

export function paddingTokenVar(token: tPaddingToken): `var(--app-padding-${tPaddingToken})` {
  return `var(--app-padding-${token})`;
}

export function resolvePaddingValue(value?: tPaddingValue) {
  if (value === undefined || value === null) {
    return undefined;
  }

  return typeof value === 'number' && isPaddingToken(value) ? paddingTokenVar(value) : value;
}
