// This file is auto-generated by scripts/generators/generateStyleContracts.js.
// Do not edit it manually. Update src/app/styles/tokens/radius.css and regenerate instead.

export const RADIUS_TOKENS = [
  'none',
  'xs',
  'sm',
  'md',
  'lg',
  'xl',
  '2xl',
  'full',
] as const;

export type tRadiusToken = (typeof RADIUS_TOKENS)[number];

export type tRadiusValue =
  | tRadiusToken
  | `var(--${string})`
  | `${number}px`
  | `${number}rem`
  | `${number}%`
  | `calc(${string})`
  | 'inherit'
  | 'initial'
  | 'unset'
  | (string & {});

const RADIUS_TOKENS_SET = new Set<string>(RADIUS_TOKENS);

export function isRadiusToken(value: string): value is tRadiusToken {
  return RADIUS_TOKENS_SET.has(value);
}

export function radiusTokenVar(token: tRadiusToken): `var(--app-radius-${tRadiusToken})` {
  return `var(--app-radius-${token})`;
}

export function resolveRadiusValue(value?: tRadiusValue) {
  if (!value) {
    return undefined;
  }

  return isRadiusToken(value) ? radiusTokenVar(value) : value;
}
