// This file is auto-generated by scripts/generators/generateStyleContracts.js.
// Do not edit it manually. Update src/app/styles/tokens/safearea.css and regenerate instead.

export const SAFE_AREA_TOKENS = [
  'top',
  'right',
  'bottom',
  'left',
  'horizontal',
  'vertical',
] as const;

export type tSafeAreaToken = (typeof SAFE_AREA_TOKENS)[number];

export type tSafeAreaValue =
  | tSafeAreaToken
  | `var(--${string})`
  | `${number}px`
  | `${number}rem`
  | `${number}%`
  | `calc(${string})`
  | 'auto'
  | 'inherit'
  | 'initial'
  | 'unset'
  | (string & {});

const SAFE_AREA_TOKENS_SET = new Set<string>(SAFE_AREA_TOKENS);

export function isSafeAreaToken(value: string): value is tSafeAreaToken {
  return SAFE_AREA_TOKENS_SET.has(value);
}

export function safeAreaTokenVar(token: tSafeAreaToken): `var(--app-safe-area-${tSafeAreaToken})` {
  return `var(--app-safe-area-${token})`;
}

export function resolveSafeAreaValue(value?: tSafeAreaValue) {
  if (!value) {
    return undefined;
  }

  return isSafeAreaToken(value) ? safeAreaTokenVar(value) : value;
}
